spring.application.name=MD_Luxury_2

# Cấu hình cổng chạy ứng dụng
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-damfck740ujc73ao5dbg-a.oregon-postgres.render.com:5432/md_luxury_db
spring.datasource.username=md_luxury_db_user
spring.datasource.password=9ybkFROfHz6NxKBHltPUPBW7kI9n6c7a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=content
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=crm-scheduler-

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600000   # 10 phút (tính bằng ms)

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqps://rksbxlea:kbcXjOAegUZhe7SaHU0_3iofqin9d1oX@armadillo.rmq.cloudamqp.com/rksbxlea}
spring.rabbitmq.listener.simple.acknowledge-mode=auto